//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleteUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AthleteUser()
        {
            this.PastHealthAnswers = new HashSet<PastHealthAnswers>();
            this.QuestionnaireResponse = new HashSet<QuestionnaireResponse>();
        }
    
        public string ID { get; set; }
        public int AthleteID { get; set; }
        public string AthleteNumber { get; set; }
        public string Password { get; set; }
        public string Name { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Email { get; set; }
        public string SportSpecialization { get; set; }
        public Nullable<bool> Registered { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public int GenderID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PastHealthAnswers> PastHealthAnswers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireResponse> QuestionnaireResponse { get; set; }
    }
}
