//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AthleticTrainer
    {
        public int ID { get; set; }
        public string ATName { get; set; }
        public string Title { get; set; }
        public string Department { get; set; }
        public string Expertise { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
