//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HealthQuestionnaireEntities : DbContext
    {
        public HealthQuestionnaireEntities()
            : base("name=HealthQuestionnaireEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllergicHistory> AllergicHistory { get; set; }
        public virtual DbSet<AthleteUser> AthleteUser { get; set; }
        public virtual DbSet<FamilyHistory> FamilyHistory { get; set; }
        public virtual DbSet<FemaleQuestionnaire> FemaleQuestionnaire { get; set; }
        public virtual DbSet<PasswordReset> PasswordReset { get; set; }
        public virtual DbSet<PastDrugs> PastDrugs { get; set; }
        public virtual DbSet<PastHealth> PastHealth { get; set; }
        public virtual DbSet<PastHealthAnswers> PastHealthAnswers { get; set; }
        public virtual DbSet<PastHistory> PastHistory { get; set; }
        public virtual DbSet<PastSupplements> PastSupplements { get; set; }
        public virtual DbSet<PresentIllness> PresentIllness { get; set; }
        public virtual DbSet<SurgeryHistory> SurgeryHistory { get; set; }
    }
}
