//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastInjuryRecord
    {
        public int PastInjuryRecordId { get; set; }
        public int PastInjuryStatusId { get; set; }
        public int PastInjuryTypeId { get; set; }
    
        public virtual PastInjuryStatus PastInjuryStatus { get; set; }
        public virtual PastInjuryType PastInjuryType { get; set; }
    }
}
