//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PastInjuryType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PastInjuryType()
        {
            this.PastInjuryRecord = new HashSet<PastInjuryRecord>();
        }
    
        public int PastInjuryTypeId { get; set; }
        public int PastInjuryCategoryId { get; set; }
        public string InjuryName { get; set; }
    
        public virtual PastInjuryCategory PastInjuryCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PastInjuryRecord> PastInjuryRecord { get; set; }
    }
}
