//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireResponses
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionnaireResponses()
        {
            this.ResponseAllergicHistory = new HashSet<ResponseAllergicHistory>();
            this.ResponseCardiovascularScreening = new HashSet<ResponseCardiovascularScreening>();
            this.ResponseConcussionScreening = new HashSet<ResponseConcussionScreening>();
            this.ResponseConcussionMedication = new HashSet<ResponseConcussionMedication>();
            this.ResponseConcentration = new HashSet<ResponseConcentration>();
            this.ResponseCoordinationAndBalance = new HashSet<ResponseCoordinationAndBalance>();
            this.ResponseDelayedRecall = new HashSet<ResponseDelayedRecall>();
            this.ResponseFamilyHistory = new HashSet<ResponseFamilyHistory>();
            this.ResponseFemaleQuestionnaire = new HashSet<ResponseFemaleQuestionnaire>();
            this.ResponseInjury = new HashSet<ResponseInjury>();
            this.ResponseImmediateMemory = new HashSet<ResponseImmediateMemory>();
            this.ResponseOrthopaedicScreening = new HashSet<ResponseOrthopaedicScreening>();
            this.ResponseOrientation = new HashSet<ResponseOrientation>();
            this.ResponsePastHistory = new HashSet<ResponsePastHistory>();
            this.ResponsePresentIllness = new HashSet<ResponsePresentIllness>();
            this.ResponsePastDrugs = new HashSet<ResponsePastDrugs>();
            this.ResponsePastHealth = new HashSet<ResponsePastHealth>();
            this.ResponseSupplements = new HashSet<ResponseSupplements>();
            this.ResponseSymptomEvaluation = new HashSet<ResponseSymptomEvaluation>();
            this.ResponseTotalScores = new HashSet<ResponseTotalScores>();
        }
    
        public int Id { get; set; }
        public string Specialist { get; set; }
        public string FillName { get; set; }
        public string AtheNum { get; set; }
        public int Gender { get; set; }
        public System.DateTime FillDate { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseAllergicHistory> ResponseAllergicHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseCardiovascularScreening> ResponseCardiovascularScreening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseConcussionScreening> ResponseConcussionScreening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseConcussionMedication> ResponseConcussionMedication { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseConcentration> ResponseConcentration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseCoordinationAndBalance> ResponseCoordinationAndBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseDelayedRecall> ResponseDelayedRecall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseFamilyHistory> ResponseFamilyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseFemaleQuestionnaire> ResponseFemaleQuestionnaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseInjury> ResponseInjury { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseImmediateMemory> ResponseImmediateMemory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseOrthopaedicScreening> ResponseOrthopaedicScreening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseOrientation> ResponseOrientation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastHistory> ResponsePastHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePresentIllness> ResponsePresentIllness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastDrugs> ResponsePastDrugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastHealth> ResponsePastHealth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseSupplements> ResponseSupplements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseSymptomEvaluation> ResponseSymptomEvaluation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseTotalScores> ResponseTotalScores { get; set; }
    }
}
