//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionnaireResponse()
        {
            this.QuestionnaireResponseDetails = new HashSet<QuestionnaireResponseDetails>();
        }
    
        public int ID { get; set; }
        public int AthleteID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public System.DateTime FillingDate { get; set; }
        public string Specialty { get; set; }
        public string FillName { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QuestionnaireResponseDetails> QuestionnaireResponseDetails { get; set; }
        public virtual AthleteUser AthleteUser { get; set; }
    }
}
