//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuestionnaireResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public QuestionnaireResponse()
        {
            this.ResponseAllergicHistory = new HashSet<ResponseAllergicHistory>();
            this.ResponseCardiovascularScreening = new HashSet<ResponseCardiovascularScreening>();
            this.ResponseConcussionScreening = new HashSet<ResponseConcussionScreening>();
            this.ResponseCurrentInjuries = new HashSet<ResponseCurrentInjuries>();
            this.ResponseFamilyHistory = new HashSet<ResponseFamilyHistory>();
            this.ResponseFemaleQuestionnaire = new HashSet<ResponseFemaleQuestionnaire>();
            this.ResponsePastDrugs = new HashSet<ResponsePastDrugs>();
            this.ResponsePastHealth = new HashSet<ResponsePastHealth>();
            this.ResponsePastHistory = new HashSet<ResponsePastHistory>();
            this.ResponsePastInjuries = new HashSet<ResponsePastInjuries>();
            this.ResponsePastSupplements = new HashSet<ResponsePastSupplements>();
            this.ResponsePresentIllness = new HashSet<ResponsePresentIllness>();
            this.ResponseSymptomEvaluation = new HashSet<ResponseSymptomEvaluation>();
        }
    
        public int ID { get; set; }
        public string AthleteID { get; set; }
        public Nullable<int> GenderID { get; set; }
        public System.DateTime FillingDate { get; set; }
        public string Specialty { get; set; }
        public string FillName { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseAllergicHistory> ResponseAllergicHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseCardiovascularScreening> ResponseCardiovascularScreening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseConcussionScreening> ResponseConcussionScreening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseCurrentInjuries> ResponseCurrentInjuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseFamilyHistory> ResponseFamilyHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseFemaleQuestionnaire> ResponseFemaleQuestionnaire { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastDrugs> ResponsePastDrugs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastHealth> ResponsePastHealth { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastHistory> ResponsePastHistory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastInjuries> ResponsePastInjuries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePastSupplements> ResponsePastSupplements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponsePresentIllness> ResponsePresentIllness { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseSymptomEvaluation> ResponseSymptomEvaluation { get; set; }
    }
}
