//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseCoordinationAndBalance
    {
        public int Id { get; set; }
        public int QuestionnaireResponseId { get; set; }
        public string TestFoot { get; set; }
        public string TestSurface { get; set; }
        public string Footwear { get; set; }
        public Nullable<int> DoubleLegError { get; set; }
        public Nullable<int> TandemError { get; set; }
        public Nullable<int> SingleLegError { get; set; }
        public Nullable<double> FirstTime { get; set; }
        public Nullable<double> SecondTime { get; set; }
        public Nullable<double> ThirdTime { get; set; }
        public Nullable<double> AverageTime { get; set; }
        public Nullable<double> FastestTime { get; set; }
        public Nullable<int> TotalErrors { get; set; }
    
        public virtual QuestionnaireResponses QuestionnaireResponses { get; set; }
    }
}
