//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResponseCoordinationAndBalance
    {
        public int ID { get; set; }
        public int TrainerQuestionnaireResponseID { get; set; }
        public string TestFoot { get; set; }
        public string TestSurface { get; set; }
        public string Footwear { get; set; }
        public int DoubleLegError { get; set; }
        public int TandemError { get; set; }
        public int SingleLegError { get; set; }
        public int TotalErrors { get; set; }
        public double FirstTime { get; set; }
        public double SecondTime { get; set; }
        public double ThirdTime { get; set; }
        public double AverageTime { get; set; }
        public double FastestTime { get; set; }
    
        public virtual TrainerQuestionnaireResponse TrainerQuestionnaireResponse { get; set; }
    }
}
