//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SymptomEvaluation
    {
        public int ID { get; set; }
        public string SymptomItem { get; set; }
        public Nullable<int> ItemScore0 { get; set; }
        public Nullable<int> ItemScore1 { get; set; }
        public Nullable<int> ItemScore2 { get; set; }
        public Nullable<int> ItemScore3 { get; set; }
        public Nullable<int> ItemScore4 { get; set; }
        public Nullable<int> ItemScore5 { get; set; }
        public Nullable<int> ItemScore6 { get; set; }
    }
}
