//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tiss_HealthQuestionnaire.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainerQuestionnaireResponse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TrainerQuestionnaireResponse()
        {
            this.ResponseCognitiveScreening = new HashSet<ResponseCognitiveScreening>();
            this.ResponseConcentration = new HashSet<ResponseConcentration>();
            this.ResponseCoordinationAndBalance = new HashSet<ResponseCoordinationAndBalance>();
            this.ResponseDelayedRecall = new HashSet<ResponseDelayedRecall>();
            this.ResponseImmediateMemory = new HashSet<ResponseImmediateMemory>();
            this.ResponseOrthopaedicScreening = new HashSet<ResponseOrthopaedicScreening>();
        }
    
        public int ID { get; set; }
        public string TrainerID { get; set; }
        public System.DateTime FillingDate { get; set; }
        public string FillName { get; set; }
        public Nullable<int> TotalScore { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseCognitiveScreening> ResponseCognitiveScreening { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseConcentration> ResponseConcentration { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseCoordinationAndBalance> ResponseCoordinationAndBalance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseDelayedRecall> ResponseDelayedRecall { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseImmediateMemory> ResponseImmediateMemory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ResponseOrthopaedicScreening> ResponseOrthopaedicScreening { get; set; }
    }
}
